version: '3.9'

services: 

  
  php:
    depends_on: 
      - database
    build: ./docker-config/php
    image: boutique-php:7.4
    container_name: boutique_php
    ports:
      - "8080:8000"
    volumes: 
      - ./:/var/www
      - ./docker-config/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - boutique_net

  database:
    container_name: boutique_database
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boutique
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks: 
      - boutique_net

  phpmyadmin:
    depends_on: 
      - database
    image: phpmyadmin
    container_name: boutique_phpmyadmin
    ports:
      - "8888:80"
    environment: 
      - PMA_ARBITRARY=1
    networks: 
      - boutique_net
  
  mailer:
    image: schickling/mailcatcher
    container_name: boutique_mailer
    ports:
      - "1025:1025"
      - "1080:1080"
    networks: 
      - boutique_net

networks: 
  boutique_net:
volumes: 
  db_data:

